### ISSUE TITLE
Smart disk option

### ISSUE THREAD

**Issue by SteffanDavies** [mdelgadoblasco/snap2stamps#16]
@mdelgadoblasco Could you please elaborate the meaning behind the smarthdd option? Is this for optimizing hard drives and should it be left off for SSDs?

**Comment by mdelgadoblasco** [comment]
That smart disk optimization is focused on the deletion of replicated files such as coordinates, and dems bands of the different pairs, as all relate to information of the master. By doing so you may be reducing by 1/3 the total space needed on disk to complete the processing.

Another thought for future would be do to end-to-end per pair, instead of doing the processing per steps for all the secondaries sequentially. But this workflow follows the philosophy of the previous version
