### ISSUE TITLE
topsar_master_split_applyorbit.xml

### ISSUE THREAD

**Issue by keepfighting666** [mdelgadoblasco/snap2stamps#24]
when I load topsar_master_split_applyorbit.xml, something goes wrong.
![image](https://github.com/user-attachments/assets/886261d0-a5c4-4c2e-ace0-d23137390928)
I have no idea what to do to fix it

**Comment by Ehssaann** [comment]
Hello, I faced the same problem. I was wondering if your issue has been resolved?

**Comment by keepfighting666** [comment]
Which version of snap2stamps do you use?

**Comment by Ehssaann** [comment]
Hello, Thanks for the response. It is version 2.0.1|
The problem was with folder structures. I had a folder in the name of 'slaves' instead pf 'secondaries'.
Right now, I am at step 3: 'coreg and ifg' where I noting would be processed. I was wondering, could you help me with it?



![Error](https://github.com/user-attachments/assets/17e718cf-c215-4e88-bbec-d923168408af)
